In [37]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"], index=["x","y","z"])

In [43]:
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [45]:
df.head(1)

   A  B  C
x  1  2  3

In [47]:
df.tail(2)

   A  B  C
y  4  5  6
z  7  8  9

In [49]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [53]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [41]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [55]:
df.info

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [57]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [59]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [63]:
df['A'].unique()

array([1, 4, 7], dtype=int64)

In [67]:
df.shape

(3, 3)